apiVersion: batch/v1
kind: Job
metadata:
  name: curator
  namespace: logging
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        job-name: curator
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: ES_LOG_HOST
          valueFrom:
            configMapKeyRef:
              key: logging_host
              name: logging-config
        - name: ES_LOG_PORT
          valueFrom:
            configMapKeyRef:
              key: logging_port
              name: logging-config
        image: ubirch/ubirch-elastic-curator-container:latest
        imagePullPolicy: Always
        # if you want to run the curator in REAL ACTION mode enable the next line
        command: ["/usr/local/bin/curator",  "--config", "/opt/config.yml", "/opt/action_file.yml"]
        name: curator
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
            - mountPath: /opt/
              name: curator-config
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: curator-config
          configMap:
             name: curator-config
             defaultMode: 420
